// Code generated by mockery v2.14.0. DO NOT EDIT.
// Alternatively, manually implement the mock following this pattern:

package email

import (
	"github.com/stretchr/testify/mock"
)

// MockEmailService is a mock implementation of EmailService interface
type MockEmailService struct {
	mock.Mock
}

// NewMockEmailService creates a new mock instance
func NewMockEmailService() *MockEmailService {
	return &MockEmailService{}
}

// SendEmail provides a mock function with given fields: to, subject, body
func (_m *MockEmailService) SendEmail(to string, subject string, body string) error {
	ret := _m.Called(to, subject, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
} 